### PR TITLE
[phonesim] Remove QtScript based scripting support. JB#57882

### PR DESCRIPTION
**Pull request by pvuorela**
QtScript is deprecated and not spotting any use for this feature.

Could be possible to switch it to use QJSEngine but no point until
there's some clear need.

@Tomin1 @spiiroin

### CODE REVIEW

**Comment by rainemak** [comment]
Getting rid of QtScript dependency from a component is good but @Tomin1 probably knows functionality better.

**Review by spiiroin — APPROVED** [review]
Technically LGTM - clean removal of a feature, package builds ok, couple of warnings not related to these changes.
But I have no idea where/how/if the scripting feature has been used.

**Comment by Tomin1** [comment]
> Getting rid of QtScript dependency from a component is good but @Tomin1 probably knows functionality better.

I'm not sure I know much more than you. Libqofono is the component where I've seen this being used at and it doesn't use this scripting feature.

I agree with Simo that this looks pretty clean. :+1:

**Comment by pvuorela** [comment]
Still removed also dbus from .pro file config.

**Pull request merged**
